### PR TITLE
BugFix: `PricePromotion` fields

### PR DESCRIPTION
**Pull request by annakovale**
A get on:
```
departure.rooms[0].price_bands[0].prices[0].promotions[0]
```
Would throw:
```
*** AttributeError: 'PricePromotion' has no field 'id' available
```

This is because the fields were not properly copied to `PricePromotion`

Trello: https://trello.com/c/qvLlZZHX/1336-gapipy-promotions-bug

### CODE REVIEW

**Comment by bartek** [comment]
Ah, so this `klass.__dict__.items()` was no longer returning the relevant fields? I swear it used to, but I imagine it's a Python 3 change. Not sure, to be honest, but .. I think I am ok with this change. I'd add some commentary around all these hacks as to why we're doing them, as right now there's just some hanging Python 2/3 comments from me way back.

**Comment by annakovale** [comment]
@bartek it was actually this change: https://github.com/gadventures/gapipy-private/commit/2ed3f3a88661c6ca387c929e713f488b7ba5b36c#diff-52eac81cf094b62e3966fa66034320c7R17

When the order changed, users with `gapipy-private` installed would get `PricePromotion` from `gapipy-private.resources.promotions`. The gapipy-private version of `Promotion` has `property` type instead of `list` type:

https://github.com/gadventures/gapipy-private/blob/master/gapipy_private/resources/promotion.py#L11

When `klass` is the gapipy-private `Promotion`, it looks like this:

```
(Pdb) klass.__dict__.items()
[('_fill_fields', <function _fill_fields at 0x10a270de8>), ('__module__', 'gapipy_private.resources.promotion'), ('__doc__', '\n    ``promotions.agencies`` is a private, nested resource\n    '), ('_is_parent_resource', True), ('_resource_collection_fields', <property object at 0x10a27b9f0>)]
```

the `*_fields` attributes are not type list, so they were never copied over.

**Comment by annakovale** [comment]
I also discovered that `departure.rooms[0].price_bands[0].prices[0].promotions[0].products` would throw an like error with "Product does not have field ID", we need to card this issue and fix it as well. I am also not convinced why `klass` suddenly _lost_ these fields - but we have a fix that doesn't use is `__dict__`, which is more stable.

**Comment by marz619** [comment]
closing in favour of #85

**Pull request closed without merging**
